version: 1.0.0.{build}

clone_folder: c:\projects\go-abi

environment:
    GOPATH: c:\gopath

install:
    - set PATH=c:\go\bin;%PATH%
    - appveyor DownloadFile https://storage.googleapis.com/golang/go1.4.2.windows-amd64.msi
    - msiexec /i go1.4.2.windows-amd64.msi /q
    - go version
    - go env
    - mkdir gopath

build: off

test_script:
    - cd c:\projects\go-abi
    - go install ./...
    - go test -v

